{% set name = "ipycytoscape" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a25732005baa891bb6aa3c5fa50be786e3bace2dfc567e1d1f9b8c6453c70eda

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.0
    - pip
    - setuptools
    - nodejs
  run:
    - python >=3.0
    - ipywidgets >=7.5.0,<8.0.0
    - traittypes >=0.2.1,<0.3.0
    - spectate

test:
  imports:
    - ipycytoscape

about:
  home: https://github.com/QuantStack/ipycytoscape/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python implementation of the graph visualization tool Cytoscape'

extra:
  recipe-maintainers:
    - marimeireles
    - martinRenou
    - SylvainCorlay
    - rmorshea
